[project]
name = "pcb-maker"
version = "0.1.0"
description = "Naive Gerber + drill to Snapmaker 2.0 G-code prototype"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygerber>=2.4.3",
    "pyyaml>=6.0.1",
]

[project.scripts]
pcb-maker = "main:cli"
